#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 28 20:38:28 2020

@author: Chetan Patil
"""

# server properties
KAFKA_SERVERS='server1:9092,server2:9092,server3:9092'
KAFKA_SERVERS_DEV='localhost:9092'

# transaction message properties
TRANSACTION_MESSAGE_MERCHANT_ID='merchant_id'
TRANSACTION_MESSAGE_USER_ID='user_id'
TRANSACTION_MESSAGE_TRANSACTION_TIMESTAMP='transaction_ts'
TRANSACTION_MESSAGE_TRANSACTION_MILLIS='transaction_millis'
TRANSACTION_MESSAGE_TRANSACTION_AMOUNT='amount'
TRANSACTION_MESSAGE_TRANSACTION_LATITUDE='transaction_latitude'
TRANSACTION_MESSAGE_TRANSACTION_LONGITUDE='transaction_longitude'

# user location message properties
USER_LOCATION_MESSAGE_USER_ID='user_id'
USER_LOCATION_MESSAGE_TIMESTAMP='user_location_ts'
USER_LOCATION_MESSAGE_MILLIS='user_location_millis'
USER_LOCATION_MESSAGE_LATITUDE='user_location_latitude'
USER_LOCATION_MESSAGE_LONGITUDE='user_location_longitude'

# consumer json message properties
DISTANCE='DISTANCE'
ULOC_MESSAGE_USER_ID='ULOC_USER_ID'
ULOC_MESSAGE_LOCATION_TIME='USER_LOCATION_TIME'
ULOC_MESSAGE_LOCATION_MILLIS='USER_LOCATION_MILLIS'
ULOC_MESSAGE_ULOC_LATITUDE='ULOC_LATITUDE'
ULOC_MESSAGE_ULOC_LONGITUDE='ULOC_LONGITUDE'
TLOC_MESSAGE_USER_ID='USER_ID'
TLOC_MESSAGE_MERCHANT_ID='MERCHANT_ID'
TLOC_MESSAGE_TRANSACTION_TIME='TRANSACTION_TIME'
TLOC_MESSAGE_TRANSACTION_MILLIS='TRANSACTION_MILLIS'
TLOC_MESSAGE_AMOUNT='AMOUNT'
TLOC_MESSAGE_TLOC_LATITUDE='TLOC_LATITUDE'
TLOC_MESSAGE_TLOC_LONGITUDE='TLOC_LONGITUDE'

# Topic Names
TRANSACTION_TOPIC_NAME='credit_card_transaction'
USER_TOPIC_NAME='user_location'

MY_CONSUMER_GROUP='myconsumergroup'
COMBINED_TRANSACTION_USER_LOCATION_TOPIC_NAME='COMBINED_TRANSACTION_USER_LOCATION'
CONSUMER_OFFSET_RESET_EARLIEST='earliest'

